FROM stefanwalther/speedtest-exporter
ARG TARGETARCH
RUN echo "I am building for $TARGETPLATFORM"

# ARG OVERLAY_ARCH="amd64"

# FROM alpine
# ARG TARGETPLATFORM
# RUN echo "I am building for $TARGETPLATFORM"